version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly" # defaults to Monday
    reviewers:
      - "Walrussuit101"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]