const sentences = [
    "If my calculator had a history, it would be more embarrassing than my browser history.",
    "Giving directions that the mountains are to the west only works when you can see them.",
    "It was her first experience training a rainbow unicorn.",
    "The bullet pierced the window shattering it before missing Danny's head by mere millimeters.",
    "I want a giraffe, but I'm a turtle eating waffles.",
    "I used to live in my neighbor's fishpond, but the aesthetic wasn't to my taste.",
    "As you consider all the possible ways to improve yourself and the world, you notice John Travolta seems fairly unhappy.",
    "They ran around the corner to find that they had traveled back in time.",
    "The tumbleweed refused to tumble but was more than willing to prance.",
    "If eating three-egg omelets causes weight-gain, budgie eggs are a good substitute.",
    "As the asteroid hurtled toward earth, Becky was upset her dentist appointment had been canceled.",
    "Happiness can be found in the depths of chocolate pudding.",
    "No matter how beautiful the sunset, it saddened her knowing she was one day older.",
    "Wisdom is easily acquired when hiding under the bed with a saucepan on your head.",
    "She traveled because it cost the same as therapy and was a lot more enjoyable.",
    "I'm a great listener, really good with empathy vs sympathy and all that, but I hate people.",
    "She folded her handkerchief neatly.",
    "The bird had a belief that it was really a groundhog.",
    "Greetings from the real universe.",
    "Everyone was curious about the large white blimp that appeared overnight.",
    "The memory we used to share is no longer coherent.",
    "Writing a list of random sentences is harder than I initially thought it would be.",
    "She had a difficult time owning up to her own crazy self.",
    "He was all business when he wore his clown suit.",
    "The hand sanitizer was actually clear glue.",
    "She was sad to hear that fireflies are facing extinction due to artificial light, habitat loss, and pesticides.",
    "The rusty nail stood erect, angled at a 45-degree angle, just waiting for the perfect barefoot to come along.",
    "Toddlers feeding raccoons surprised even the seasoned park ranger.",
    "Peanut butter and jelly caused the elderly lady to think about her past.",
    "The waitress was not amused when he ordered green eggs and ham.",
    "Thigh-high in the water, the fisherman's hope for dinner soon turned to despair.",
    "Abstraction is often one floor above you.",
    "Nancy decided to make the porta-potty her home.",
    "The chic gangster liked to start the day with a pink scarf.",
    "The doll spun around in circles in hopes of coming alive.",
    "She wasn't sure whether to be impressed or concerned that he folded underwear in neat little packages.",
    "Various sea birds are elegant, but nothing is as elegant as a gliding pelican.",
    "Of course, she loves her pink bunny slippers.",
    "He went back to the video to see what had been recorded and was shocked at what he saw.",
    "The near-death experience brought new ideas to light.",
    "It caught him off guard that space smelled of seared steak.",
    "I just wanted to tell you I could see the love you have for your child by the way you look at her.",
    "The thunderous roar of the jet overhead confirmed her worst fears.",
    "There is no better feeling than staring at a wall with closed eyes.",
    "There are no heroes in a punk rock band.",
    "I thought red would have felt warmer in summer but I didn't think about the equator.",
    "She was disgusted he couldn't tell the difference between lemonade and limeade.",
    "The complicated school homework left the parents trying to help their kids quite confused.",
    "You realize you're not alone as you sit in your bedroom massaging your calves after a long day of playing tug-of-war with Grandpa Joe in the hospital.",
    "Had he known what was going to happen, he would have never stepped into the shower."
];

export default sentences;